set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "auth_plugin")
set(Plugin-Version "1.0.0")
set(Plugin-Description "A plugin for authentication")
set(Plugin-Vendor "Waleon")
set(Plugin-ContactAddress "https://github.com/Waleon")
set(Plugin-Category "test")