set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "fit_demo_plugin")
set(Plugin-Version "1.0.0")
set(Plugin-Description "A plugin for fit_demo entication")
set(Plugin-Vendor "Zhongbin Yu")
set(Plugin-ContactAddress "yuzhongbin@huawei.com")
set(Plugin-Category "test")
