set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "fit_add_proxy")
set(Plugin-Version "1.0.0")
set(Plugin-Description "A plugin for fit_add_proxy entication")
set(Plugin-Vendor "Zhongbin Yu")
set(Plugin-ContactAddress "yuzhongbin@huawei.com")
set(Plugin-Category "test")
